name: build-all

on:
  push:
    branches: 
      - '**'
    paths:
      - "**"

jobs:
  build-and-publish:
    uses: ./.github/workflows/build.yml
    with:
      image_tags: 'type=sha,suffix=-test'
    secrets: inherit
